# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for master and staging branches
  push:
    branches: [ staging, master ]
  pull_request:
    branches: [ staging, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y qtbase5-dev libtelepathy-qt5-dev libphonenumber-dev dbus-test-runner dconf-cli gnome-keyring libmission-control-plugins-dev libqt5sql5-sqlite libsqlite3-dev qt5-default sqlite3 telepathy-mission-control-5 doxygen

      # Runs a set of commands using the runners shell
      - name: Build libofono-qt
        run: |
           git clone https://github.com/Kaffeine/libofono-qt.git
           cd libofono-qt
           qmake && make -j4
           sudo make install
           cd ..
      - name: Build
        run: |
           mkdir build && cd build
           cmake ../
           make -j4
           make test
           ctest --output-on-failure
